version: "2"

services:

  label-studio-yolov5-backend:
    image: alyetama/label-studio-yolov5-backend:latest
    restart: always
    ports:
      - "8000:8000"
      - "9090:9090"
    environment:
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - LABEL_STUDIO_BG_LABEL=${LABEL_STUDIO_BG_LABEL}
    volumes:
      - ./weights:/app/weights
